services:
  service.api:
    image: rentalcar.service.api
    restart: always
    build:
      context: .
      dockerfile: RentalCar.Service.API/Dockerfile
    container_name: service.api
    ports:
      - "814:8080"
      - "815:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:8080;http://*:815
    depends_on:
      - service.db
    volumes:
      - service_logs:/app/logs
        
  service.db:
    image: mysql:8.0.40
    restart: always
    container_name: service.db
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Admin2k24@
      #- MYSQL_DATABASE=service_db
    volumes:
      - service_db:/var/lib/mysql
        
volumes:
  service_logs:
  service_db: