# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies API
      run: dotnet restore ./RentalCar.Service.API/RentalCar.Service.API.csproj

    - name: Restore dependencies Tests
      run: dotnet restore ./RentalCar.Service.UnitTest/RentalCar.Service.UnitTest.csproj
      
    - name: Build API
      run: dotnet build ./RentalCar.Service.API/RentalCar.Service.API.csproj --no-restore

    - name: Build Unit Test
      run: dotnet build ./RentalCar.Service.UnitTest/RentalCar.Service.UnitTest.csproj --no-restore
      
    - name: Unit Test
      run: dotnet test ./RentalCar.Service.UnitTest/RentalCar.Service.UnitTest.csproj --no-build --verbosity normal
